### ISSUE TITLE
Reduce memory usage of SecretScanner

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/SecretScanner#29]
SecretScanner takes >250 mb of memory when scanning hosts with huge number of files

**Comment by ramanan-ravi** [comment]
https://github.com/deepfence/SecretScanner/pull/28
It was saving list of all files to process in a slice which was taking lot of memory beyond 300k entries.
Now optimized that part to process the files inside `filepath.Walk` as and when we get a file.

**Comment by sandman137** [comment]
What is the current memory usage for scanning a large container image (say 1g+)?

**Comment by ramanan-ravi** [comment]
Now it takes ~60 mb for all scans
