### ISSUE TITLE
Crashed when scanning big sized image.

### ISSUE THREAD

**Issue by JackTien** [deepfence/SecretScanner#32]
Hi, I used this tool to scan an image whose size is 26.83GB, then I received a fatal error:

scanImage: Could not save container image: exit status 1. Check if the image name is correct.
main: error while scanning image: exit status 1
panic: Fatal error....

goroutine 1 [running]:
github.com/deepfence/SecretScanner/core.(*Logger).Log(0x4000800f5b, 0x5, {0x1094c61, 0x24}, {0xc00045dee8, 0x1, 0x1})
	/home/deepfence/src/SecretScanner/core/log.go:68 +0x25e
github.com/deepfence/SecretScanner/core.(*Logger).Fatal(...)
	/home/deepfence/src/SecretScanner/core/log.go:73
main.runOnce()
	/home/deepfence/src/SecretScanner/main.go:108 +0x145
main.main()
	/home/deepfence/src/SecretScanner/main.go:148 +0x114

**Comment by ramanan-ravi** [comment]
@JackTien Image is not pulled from registry by the SecretScanner. Can you check if the image is present locally in the machine where you are scanning?

**Comment by ramanan-ravi** [comment]
@JackTien Can you check if the image is present locally? Can you also ensure >120 gb hard disk?

**Comment by JackTien** [comment]
Yes, it’s stored locally and my disk space is more than 120GB.

**Comment by ramanan-ravi** [comment]
@JackTien We are checking the issue

**Comment by JackTien** [comment]
thanks. we are looking forward to receive your reply.

Ramanan Ravikumar ***@***.***> 於 2022年2月18日 週五 下午12:39寫道：

**Comment by JackTien** [comment]
Hi, I'm still waiting for your reply.  Best regards.

**Comment by shyam-dev** [comment]
Hello @JackTien - we are doing some fixes around this issue. Expect a solution for this over the next week or so

**Comment by JackTien** [comment]
Great, thanks for the update.

Shyam Krishnaswamy ***@***.***> 於 2022年2月22日 週二 下午1:14寫道：

**Comment by JackTien** [comment]
Hi, how can I update my image and test the fixed version?

**Comment by JackTien** [comment]
hi, any feedback for this is appreciate ;)

**Comment by JackTien** [comment]
@ramanan-ravi  Where can I use the fixed version of the program ?
