### ISSUE TITLE
Process gets killed when scanning 

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/SecretScanner#38]
The secret scanner process running inside agent gets Killed on VM 143.198.68.242
Process log:
```
      "Full File Name": "/fenced/mnt/host/var/snap/docker/common/var-lib-docker/overlay2/5043b3ac304141297e67251e1ce08efd890a2e0b738a4fdc0087daee3d95ca9c/diff/var/log/dpkg.log",
      "Matched Contents": ".log"
    }

Killed
```

top:
```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                       
1375878 root      20   0 1404896  40476  22884 D  19.3   1.0   0:13.14 SecretScanner  
```

The memory % and cpu usage does not grow with time.
Issue has been produced only in this VM

**Comment by deviprasad303** [comment]
@saurabh2253 what kind of vm is it . we are ignoring paths like var/lib/docker and all the overlays; here in this var/lib/docker is taking path as var-lib-docker. we should ignore it. can we get access to this vm and is this part of host scan
